### ISSUE TITLE
Drag and drop is broken in Moodle and H5P.org?

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-drag-n-drop#1]
Hello,

Is Drag and Drop (1.11.4) broken on h5p.org and in Moodle or is it just me?

What I did do;

1. Created drag and drop 
2. Set background image
3. Created dropzone "hull dropzone" and placed it in the hull part of the image
4. Created text "hull"
5. Saved
6. Now if I drag hull text to "hull dropzone" and check i get -1 points.

**Here is the file**

[test-23-11-147840.zip](https://github.com/h5p/h5p-drag-n-drop/files/1498615/test-23-11-147840.zip)

![drag1](https://user-images.githubusercontent.com/15193418/33167449-40985932-d046-11e7-9985-3db82b76c955.PNG)

![drag2](https://user-images.githubusercontent.com/15193418/33167457-454c92d6-d046-11e7-80ac-2d4ac2b9448e.PNG)

![drag3](https://user-images.githubusercontent.com/15193418/33167462-48bbfe48-d046-11e7-86d6-bb52136def14.PNG)

![drag4](https://user-images.githubusercontent.com/15193418/33167465-4bccc112-d046-11e7-9b15-49f500325715.PNG)

![drag5](https://user-images.githubusercontent.com/15193418/33167495-621e51ba-d046-11e7-9798-f4dd7b98775a.PNG)

**Comment by icc** [comment]
I'm sorry, but I'm not sure that I'm seeing the problem here.
What was the expected outcome of what you did?

**Comment by Jarvil** [comment]
Hello,

I excpeted to receive 1 point (for correctly matcing the drop text with the assigned drop zone) instead of one negative point.

**Comment by icc** [comment]
From the screenshots, it looks like you forgot to edit the 'Hull dropzone' and select which of the draggable elements are correct, i.e. you must check those that should receive points when dropped in the dropzone.

**Comment by Jarvil** [comment]
Hello,

That was it, thank you for the tip, this can close now.
